In [1]:
import numpy as np

In [35]:
a = np.zeros(8)
a+=1

In [28]:
b = np.asarray(range(0,8))

In [29]:
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
a

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
sum(a *b)

28.0

In [36]:
import numpy as np

# Create the first matrix (all 1s)
#a = np.ones((8, 8), dtype=int)

# Create the second matrix (numbers 0 to 63 in row-major order)
b = np.arange(64).reshape(8, 8)



In [39]:
a.dot(b)

array([224., 232., 240., 248., 256., 264., 272., 280.])